# # recuperer les informations qui sont dans le conteneur nginx
# # pour cela on va utiliser la commande docker inspect
# # docker inspect <container_id> | grep IPAddress
# # cela va nous donner l'adresse IP du conteneur nginx
# # ensuite on va utiliser cette adresse IP pour configurer le proxy_pass dans le fichier nginx.conf


events {}

http {
    server {
        listen 80; # on va écouter sur le port 80 pour les requêtes entrantes
        server_name localhost; # on va définir le nom de domaine pour que le serveur nginx puisse savoir quelle est la requête qui a été faite

        location / {
            proxy_pass http://node:4000; # on va utiliser le nom du service node qui est défini dans le docker-compose.yml
            proxy_set_header Host $host; # on va définir l'en-tête Host pour que le serveur Node puisse savoir quelle est la requête qui a été faite
            proxy_set_header X-Real-IP $remote_addr; # on va définir l'en-tête X-Real-IP pour que le serveur Node puisse savoir quelle est l'adresse IP du client qui a fait la requête
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # on va définir l'en-tête X-Forwarded-For pour que le serveur Node puisse savoir quelle est l'adresse IP du client qui a fait la requête
            proxy_set_header X-Forwarded-Proto $scheme; # on va définir l'en-tête X-Forwarded-Proto pour que le serveur Node puisse savoir quel est le protocole utilisé pour faire la requête (http ou https)
        }
    }
}
